<?php

use RealPress\Helpers\Settings;

return array(
	'post_types'    => apply_filters(
		'realpress/config/post_types',
		array(
			REALPRESS_PROPERTY_CPT => array(
				'labels'                => array(
					'name'               => _x( 'RealPress Properties', 'admin menu', 'realpress' ),
					'singular_name'      => _x( 'Property', 'admin menu', 'realpress' ),
					'menu_name'          => _x( 'RealPress', 'admin bar', 'realpress' ),
					'name_admin_bar'     => _x( 'Property', 'realpress' ),
					'add_new'            => esc_html__( 'Add New', 'realpress' ),
					'add_new_item'       => esc_html__( 'Add New Property', 'realpress' ),
					'new_item'           => esc_html__( 'New Property', 'realpress' ),
					'edit_item'          => esc_html__( 'Edit Property', 'realpress' ),
					'view_item'          => esc_html__( 'View Property', 'realpress' ),
					'all_items'          => esc_html__( 'All Properties', 'realpress' ),
					'search_items'       => esc_html__( 'Search Properties', 'realpress' ),
					'parent_item_colon'  => esc_html__( 'Parent Properties:', 'realpress' ),
					'not_found'          => esc_html__( 'No Properties found.', 'realpress' ),
					'not_found_in_trash' => esc_html__( 'No Properties found in Trash.', 'realpress' ),
				),
				'description'           => esc_html__( 'Description.', 'realpress' ),
				'public'                => true,
				'menu_icon'             => 'dashicons-building',
				'publicly_queryable'    => true,
				'show_ui'               => true,
				'show_in_menu'          => true,
				'query_var'             => true,
				'show_in_rest'          => true,
				'rest_base'             => 'realpress-property',
				'rest_controller_class' => 'WP_REST_Posts_Controller',
				'rewrite'               => array(
					'slug'       => Settings::get_property_slug(),
					'with_front' => false,
				),
				'map_meta_cap'          => true,
				'has_archive'           => true,
				'hierarchical'          => false,
				'menu_position'         => null,
				'taxonomies'            => array( 'category', 'post_tag' ),
				'supports'              => array(
					'title',
					'editor',
					'author',
					'thumbnail',
					'excerpt',
					'comments',
					'custom-fields',
					'page-attributes',
				),
				'capability_type'       => array(
					REALPRESS_PROPERTY_CPT,
					'realpress-properties',
				),
			),
		)
	),
	'taxonomies'    => apply_filters(
		'realpress/config/taxonomies',
		array(
			'realpress-type'         => array(
				'hierarchical'          => true,
				'show_ui'               => true,
				'show_in_rest'          => true,
				'rest_base'             => 'realpress-type',
				'rest_controller_class' => 'WP_REST_Terms_Controller',
				'show_admin_column'     => true,
				'query_var'             => true,
				'rewrite'               => array(
					'slug' => 'realpress-type',
				),
				'post_types'            => array( REALPRESS_PROPERTY_CPT ),
				'labels'                => array(
					'name'              => _x( 'Property Type', 'taxonomy general name', 'realpress' ),
					'singular_name'     => _x( 'Property Type', 'taxonomy singular name', 'realpress' ),
					'search_items'      => esc_html__( 'Search Property Type', 'realpress' ),
					'all_items'         => esc_html__( 'All Property Type', 'realpress' ),
					'parent_item'       => esc_html__( 'Parent Property Type', 'realpress' ),
					'parent_item_colon' => esc_html__( 'Parent Property Type:', 'realpress' ),
					'edit_item'         => esc_html__( 'Edit Property Type', 'realpress' ),
					'update_item'       => esc_html__( 'Update Property Type', 'realpress' ),
					'add_new_item'      => esc_html__( 'Add New Property Type', 'realpress' ),
					'new_item_name'     => esc_html__( 'New Property Type Name', 'realpress' ),
					'menu_name'         => esc_html__( 'Property Type', 'realpress' ),
				),
			),
			'realpress-location'     => array(
				'hierarchical'          => true,
				'show_ui'               => true,
				'show_in_rest'          => true,
				'rest_base'             => 'realpress-location',
				'rest_controller_class' => 'WP_REST_Terms_Controller',
				'show_admin_column'     => true,
				'query_var'             => true,
				'rewrite'               => array(
					'slug' => 'realpress-location',
				),
				'post_types'            => array( REALPRESS_PROPERTY_CPT ),
				'labels'                => array(
					'name'              => _x( 'Property Location', 'taxonomy general name', 'realpress' ),
					'singular_name'     => _x( 'Property Location', 'taxonomy singular name', 'realpress' ),
					'search_items'      => esc_html__( 'Search Property Location', 'realpress' ),
					'all_items'         => esc_html__( 'All Property Location', 'realpress' ),
					'parent_item'       => esc_html__( 'Parent Property Location', 'realpress' ),
					'parent_item_colon' => esc_html__( 'Parent Property Location:', 'realpress' ),
					'edit_item'         => esc_html__( 'Edit Property Location', 'realpress' ),
					'update_item'       => esc_html__( 'Update Property Location', 'realpress' ),
					'add_new_item'      => esc_html__( 'Add New Property Location', 'realpress' ),
					'new_item_name'     => esc_html__( 'New Property Location Name', 'realpress' ),
					'menu_name'         => esc_html__( 'Property Location', 'realpress' ),
				),
			),
			'realpress-feature'      => array(
				'hierarchical'          => true,
				'show_ui'               => true,
				'show_in_rest'          => true,
				'rest_base'             => 'realpress-feature',
				'rest_controller_class' => 'WP_REST_Terms_Controller',
				'show_admin_column'     => true,
				'query_var'             => true,
				'rewrite'               => array(
					'slug' => 'realpress-feature',
				),
				'post_types'            => array( REALPRESS_PROPERTY_CPT ),
				'labels'                => array(
					'name'              => _x( 'Property Feature', 'taxonomy general name', 'realpress' ),
					'singular_name'     => _x( 'Property Feature', 'taxonomy singular name', 'realpress' ),
					'search_items'      => esc_html__( 'Search Property Feature', 'realpress' ),
					'all_items'         => esc_html__( 'All Property Feature', 'realpress' ),
					'parent_item'       => esc_html__( 'Parent Property Feature', 'realpress' ),
					'parent_item_colon' => esc_html__( 'Parent Property Feature:', 'realpress' ),
					'edit_item'         => esc_html__( 'Edit Property Feature', 'realpress' ),
					'update_item'       => esc_html__( 'Update Property Feature', 'realpress' ),
					'add_new_item'      => esc_html__( 'Add New Property Feature', 'realpress' ),
					'new_item_name'     => esc_html__( 'New Property Feature Name', 'realpress' ),
					'menu_name'         => esc_html__( 'Property Feature', 'realpress' ),
				),
			),
			'realpress-status'       => array(
				'hierarchical'          => true,
				'show_ui'               => true,
				'show_in_rest'          => true,
				'rest_base'             => 'realpress-status',
				'rest_controller_class' => 'WP_REST_Terms_Controller',
				'show_admin_column'     => true,
				'query_var'             => true,
				'rewrite'               => array(
					'slug' => 'realpress-status',
				),
				'post_types'            => array( REALPRESS_PROPERTY_CPT ),
				'labels'                => array(
					'name'              => _x( 'Status', 'taxonomy general name', 'realpress' ),
					'singular_name'     => _x( 'Status', 'taxonomy singular name', 'realpress' ),
					'search_items'      => esc_html__( 'Search Status', 'realpress' ),
					'all_items'         => esc_html__( 'All Status', 'realpress' ),
					'parent_item'       => esc_html__( 'Parent Status', 'realpress' ),
					'parent_item_colon' => esc_html__( 'Parent Status:', 'realpress' ),
					'edit_item'         => esc_html__( 'Edit Status', 'realpress' ),
					'update_item'       => esc_html__( 'Update Status', 'realpress' ),
					'add_new_item'      => esc_html__( 'Add New Status', 'realpress' ),
					'new_item_name'     => esc_html__( 'New Status Name', 'realpress' ),
					'menu_name'         => esc_html__( 'Status', 'realpress' ),
				),
			),
			'realpress-energy-class' => array(
				'hierarchical'          => true,
				'show_ui'               => true,
				'show_in_rest'          => true,
				'rest_base'             => 'realpress-energy-class',
				'rest_controller_class' => 'WP_REST_Terms_Controller',
				'show_admin_column'     => true,
				'query_var'             => true,
				'rewrite'               => array(
					'slug' => 'realpress-energy-class',
				),
				'post_types'            => array( REALPRESS_PROPERTY_CPT ),
				'labels'                => array(
					'name'              => _x( 'Energy Class', 'taxonomy general name', 'realpress' ),
					'singular_name'     => _x( 'Energy Class', 'taxonomy singular name', 'realpress' ),
					'search_items'      => esc_html__( 'Search Energy Class', 'realpress' ),
					'all_items'         => esc_html__( 'All Energy Class', 'realpress' ),
					'parent_item'       => esc_html__( 'Parent Energy Class', 'realpress' ),
					'parent_item_colon' => esc_html__( 'Parent Energy Class:', 'realpress' ),
					'edit_item'         => esc_html__( 'Edit Energy Class', 'realpress' ),
					'update_item'       => esc_html__( 'Update Energy Class', 'realpress' ),
					'add_new_item'      => esc_html__( 'Add New Energy Class', 'realpress' ),
					'new_item_name'     => esc_html__( 'New Energy Class Name', 'realpress' ),
					'menu_name'         => esc_html__( 'Energy Class', 'realpress' ),
				),
			),
			'realpress-labels'       => array(
				'hierarchical'          => true,
				'show_ui'               => true,
				'show_in_rest'          => true,
				'rest_base'             => 'realpress-labels',
				'rest_controller_class' => 'WP_REST_Terms_Controller',
				'show_admin_column'     => true,
				'query_var'             => true,
				'rewrite'               => array(
					'slug' => 'realpress-labels',
				),
				'post_types'            => array( REALPRESS_PROPERTY_CPT ),
				'labels'                => array(
					'name'              => _x( 'Labels', 'taxonomy general name', 'realpress' ),
					'singular_name'     => _x( 'Labels', 'taxonomy singular name', 'realpress' ),
					'search_items'      => esc_html__( 'Search Labels', 'realpress' ),
					'all_items'         => esc_html__( 'All Labels', 'realpress' ),
					'parent_item'       => esc_html__( 'Parent Labels', 'realpress' ),
					'parent_item_colon' => esc_html__( 'Parent Labels:', 'realpress' ),
					'edit_item'         => esc_html__( 'Edit Labels', 'realpress' ),
					'update_item'       => esc_html__( 'Update Labels', 'realpress' ),
					'add_new_item'      => esc_html__( 'Add New Labels', 'realpress' ),
					'new_item_name'     => esc_html__( 'New Labels Name', 'realpress' ),
					'menu_name'         => esc_html__( 'Labels', 'realpress' ),
				),
			),
		)
	),
	'post_statuses' => apply_filters(
		'realpress/config/statuses',
		array(
			'reject' => array(
				'label'                     => esc_html__( 'Reject', 'realpress' ),
				'public'                    => false,
				'protected'                 => true,
				'exclude_from_search'       => false,
				'private'                   => true,
				'show_in_admin_all_list'    => true,
				'icon'                      => 'la la-refresh',
				'show_in_admin_status_list' => true,
				'label_count'               => _n_noop(
					'Reject <span class="count">(%s)</span>',
					'Reject <span class="count">(%s)</span>',
					'realpress'
				),
			),
		)
	),
);

